# Generated by Django 3.0.1 on 2021-01-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyfeatures',
            name='feature_1_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='keyfeatures',
            name='feature_2_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='keyfeatures',
            name='feature_3_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='keyfeatures',
            name='feature_4_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='keyfeatures',
            name='feature_5_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='keyfeatures',
            name='feature_1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='keyfeatures',
            name='feature_2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='keyfeatures',
            name='feature_3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='keyfeatures',
            name='feature_4',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='keyfeatures',
            name='feature_5',
            field=models.TextField(blank=True),
        ),
    ]
