# Generated by Django 3.0.1 on 2021-01-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_auto_20210124_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyfeatures',
            name='feature_1',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='keyfeatures',
            name='feature_1_name',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='keyfeatures',
            name='feature_2',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='keyfeatures',
            name='feature_2_name',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='keyfeatures',
            name='feature_3',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='keyfeatures',
            name='feature_3_name',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='keyfeatures',
            name='feature_4',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='keyfeatures',
            name='feature_4_name',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='keyfeatures',
            name='feature_5',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='keyfeatures',
            name='feature_5_name',
            field=models.CharField(max_length=254),
        ),
    ]
