# Generated by Django 3.0.1 on 2021-01-24 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0005_auto_20210124_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyfeatures',
            name='feature_5',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='keyfeatures',
            name='feature_5_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_5_names', to='setup.Feature'),
        ),
    ]
