# Generated by Django 3.0.1 on 2021-01-23 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(max_length=254, null=True)),
                ('has_logo', models.BooleanField(default=True, null=True)),
                ('brand_logo', models.ImageField(null=True, upload_to='')),
                ('has_side_banner', models.BooleanField(blank=True, default=False, null=True)),
                ('side_banner', models.ImageField(blank=True, null=True, upload_to='')),
                ('website', models.URLField(max_length=1024, null=True)),
            ],
            options={
                'verbose_name_plural': 'Brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KeyFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
                ('feature_1', models.TextField()),
                ('feature_2', models.TextField()),
                ('feature_3', models.TextField()),
                ('feature_4', models.TextField()),
                ('feature_5', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Key Features',
            },
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Memorys',
            },
        ),
    ]
