# Generated by Django 3.0.1 on 2021-01-24 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Feature Name',
            },
        ),
        migrations.AlterField(
            model_name='keyfeatures',
            name='feature_1',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='keyfeatures',
            name='feature_2',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='keyfeatures',
            name='feature_3',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='keyfeatures',
            name='feature_4',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='keyfeatures',
            name='feature_5',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='keyfeatures',
            name='feature_1_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_1_names', to='setup.Feature'),
        ),
        migrations.AddField(
            model_name='keyfeatures',
            name='feature_2_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_2_names', to='setup.Feature'),
        ),
        migrations.AddField(
            model_name='keyfeatures',
            name='feature_3_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_3_names', to='setup.Feature'),
        ),
        migrations.AddField(
            model_name='keyfeatures',
            name='feature_4_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_4_names', to='setup.Feature'),
        ),
        migrations.AddField(
            model_name='keyfeatures',
            name='feature_5_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_5_names', to='setup.Feature'),
        ),
    ]
