# Generated by Django 3.0.1 on 2021-01-24 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_auto_20210124_0953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name_plural': 'Features'},
        ),
    ]
