# Generated by Django 3.0.1 on 2021-01-24 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0003_auto_20210124_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyfeatures',
            name='friendly_name',
        ),
        migrations.AddField(
            model_name='keyfeatures',
            name='features_for',
            field=models.CharField(blank=True, default='"Motherboard, Graphic Card, Power Supply" * ', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(default='nesto', max_length=254),
        ),
        migrations.AlterField(
            model_name='keyfeatures',
            name='feature_5_name',
            field=models.ForeignKey(blank=True, default='test1', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_5_names', to='setup.Feature'),
        ),
    ]
