# Generated by Django 3.0.1 on 2021-01-24 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0004_auto_20210124_2255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyfeatures',
            old_name='features_for',
            new_name='feature_for',
        ),
    ]
