# Generated by Django 3.0.1 on 2021-01-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0006_auto_20210125_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='TestSpec', max_length=254)),
            ],
            options={
                'verbose_name_plural': 'TestSpec',
            },
        ),
    ]
