# Generated by Django 3.0.1 on 2021-01-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0009_auto_20210125_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='has_logo',
        ),
        migrations.AlterField(
            model_name='keyfeatures',
            name='feature_for',
            field=models.CharField(blank=True, default='Motherboard, Graphic Card etc. ', max_length=254),
        ),
    ]
