# Generated by Django 3.0.1 on 2021-01-23 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
        ('products', '0024_auto_20210123_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='key_features',
        ),
        migrations.AddField(
            model_name='product',
            name='key_feature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='key_features', to='setup.KeyFeatures'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brands', to='setup.Brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufacturer_logos', to='setup.Brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='memory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memorys', to='setup.Memory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='processor_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processor_brands', to='setup.Brand'),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='KeyFeatures',
        ),
        migrations.DeleteModel(
            name='Memory',
        ),
    ]
