# Generated by Django 3.0.1 on 2021-01-24 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
        ('products', '0025_auto_20210123_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='processor_brand',
            new_name='additional_ogo',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='side_banner',
            new_name='promo_side_banner_bottom',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='manufacturer_logo',
        ),
        migrations.RemoveField(
            model_name='product',
            name='memory',
        ),
        migrations.AddField(
            model_name='product',
            name='chipset_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chipset_logos', to='setup.Brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='promo_side_banner_left',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='promo_side_banner_right',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.TextField(default=False),
        ),
    ]
