# Generated by Django 3.0.1 on 2021-01-25 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_remove_product_testspec'),
        ('setup', '0008_auto_20210125_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Specs', to='setup.Specification'),
        ),
    ]
