# Generated by Django 3.0.1 on 2021-01-25 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0009_auto_20210125_1633'),
        ('products', '0032_product_specification'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='specification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Specs', to='setup.Specification'),
        ),
    ]
